=== rishabhtandon31/Java/DBMS_WORK/1559950_Rishabh_Tandon/xml/mpt1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/mpt1" xmlns:tns="http://www.example.org/mpt1" elementFormDefault="qualified">
<element name="electricity_Consumer">
<complexType>
	<sequence>
		
			<element name="consumerNo">
			<simpleType>
				<restriction base="integer">
					<pattern value="[0-9]{8}"/>
					<totalDigits value="8"/>
				</restriction>
			</simpleType>
			</element>
			<element name="ConsumerName">
			<simpleType>
				<restriction base="string">
					<maxLength value="20"></maxLength>
					<pattern value="[A-Z]{1}[A-Za-z]{2,}"/>
				</restriction>
			</simpleType>
			</element>
			<element name="emailId" type="string">
			<simpleType>
				<restriction base="string">
					<maxLength value="35"></maxLength>
				</restriction>
			</simpleType>
			</element>
			<element name="UnitsConsumed">
			<simpleType>
				<restriction base="integer">
					<minInclusive value="0"/>
				</restriction>
			</simpleType>
			</element>
		
	</sequence>
</complexType>
</element>
</schema>

=== rishabhtandon31/Java/DBMS_WORK/1559950_Rishabh_Tandon/xml/mpt1.xml
<?xml version="1.0" encoding="UTF-8"?>
<electricity_Consumer xmlns="http://www.example.org/mpt1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/mpt1 mpt1.xsd ">
  <consumerNo>1001</consumerNo>
  <ConsumerName>Seema Joshi</ConsumerName>
  <emailId>Seema.joshi@gmail.com</emailId>
  <UnitsConsumed>250</UnitsConsumed>
</electricity_Consumer>

<electricity_Consumer xmlns="http://www.example.org/mpt1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/mpt1 mpt1.xsd ">
  <consumerNo>1002</consumerNo>
  <ConsumerName>Amey Joshi</ConsumerName>
  <emailId>Amey.j@cg.com</emailId>
  <UnitsConsumed>345</UnitsConsumed>
</electricity_Consumer>

<electricity_Consumer xmlns="http://www.example.org/mpt1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/mpt1 mpt1.xsd ">
  <consumerNo>1003</consumerNo>
  <ConsumerName>Pravin</ConsumerName>
  <emailId>Pravin.t@cg.com</emailId>
  <UnitsConsumed>457</UnitsConsumed>
</electricity_Consumer>

<electricity_Consumer xmlns="http://www.example.org/mpt1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/mpt1 mpt1.xsd ">
  <consumerNo>1004</consumerNo>
  <ConsumerName>Manoj Kulkarni</ConsumerName>
  <emailId>maonj@gmail.com</emailId>
  <UnitsConsumed>780</UnitsConsumed>
</electricity_Consumer>

<electricity_Consumer xmlns="http://www.example.org/mpt1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/mpt1 mpt1.xsd ">
  <consumerNo>1005</consumerNo>
  <ConsumerName>Shrikant Shinde</ConsumerName>
  <emailId>Shrikant.shinde@gmail.com</emailId>
  <UnitsConsumed>90</UnitsConsumed>
</electricity_Consumer>

<electricity_Consumer xmlns="http://www.example.org/mpt1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/mpt1 mpt1.xsd ">
  <consumerNo>1006</consumerNo>
  <ConsumerName>Mahesh B</ConsumerName>
  <emailId>bMahesh@yahoo.com</emailId>
  <UnitsConsumed>720</UnitsConsumed>
</electricity_Consumer>
